# Generated by Django 5.2.2 on 2025-06-27 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                ("idcliente", models.AutoField(primary_key=True, serialize=False)),
                ("nombres", models.CharField(max_length=40)),
                ("apellidos", models.CharField(max_length=40)),
                ("direccion", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("telefono", models.CharField(max_length=15)),
                ("estado", models.BooleanField(default=True)),
            ],
        ),
    ]
