# Generated by Django 5.2.3 on 2025-06-28 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                ("idcategoria", models.AutoField(primary_key=True, serialize=False)),
                ("descripcion", models.CharField(max_length=30, unique=True)),
                ("estado", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
                "db_table": "categorias",
                "ordering": ["descripcion"],
            },
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                ("idcliente", models.AutoField(primary_key=True, serialize=False)),
                ("ruc_dni", models.CharField(max_length=11, unique=True)),
                ("nombres", models.CharField(max_length=80)),
                ("direccion", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("estado", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "clientes",
            },
        ),
        migrations.CreateModel(
            name="Tipo",
            fields=[
                ("idtipo", models.AutoField(primary_key=True, serialize=False)),
                ("descripcion", models.CharField(max_length=20, unique=True)),
                ("estado", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "tipos",
            },
        ),
        migrations.CreateModel(
            name="Unidad",
            fields=[
                ("idunidad", models.AutoField(primary_key=True, serialize=False)),
                ("descripcion", models.CharField(max_length=30, unique=True)),
                ("estado", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "unidades",
            },
        ),
        migrations.CreateModel(
            name="CabeceraVenta",
            fields=[
                ("idventa", models.AutoField(primary_key=True, serialize=False)),
                ("fecha_venta", models.DateField()),
                ("total", models.FloatField()),
                ("subtotal", models.FloatField()),
                ("igv", models.FloatField()),
                ("nrodoc", models.CharField(max_length=12)),
                ("estado", models.BooleanField(default=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        db_column="idcliente",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ventasApp.cliente",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        db_column="idtipo",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ventasApp.tipo",
                    ),
                ),
            ],
            options={
                "db_table": "cabeceraventas",
            },
        ),
        migrations.CreateModel(
            name="Parametro",
            fields=[
                (
                    "tipo",
                    models.OneToOneField(
                        db_column="idtipo",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="ventasApp.tipo",
                    ),
                ),
                ("numeracion", models.CharField(max_length=15, unique=True)),
                ("serie", models.CharField(max_length=3)),
            ],
            options={
                "db_table": "parametros",
            },
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                ("idproducto", models.AutoField(primary_key=True, serialize=False)),
                ("descripcion", models.CharField(max_length=40, unique=True)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("cantidad", models.IntegerField()),
                ("estado", models.BooleanField(default=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        db_column="idcategoria",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ventasApp.categoria",
                    ),
                ),
                (
                    "unidad",
                    models.ForeignKey(
                        db_column="idunidad",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ventasApp.unidad",
                    ),
                ),
            ],
            options={
                "db_table": "productos",
            },
        ),
        migrations.CreateModel(
            name="DetalleVenta",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "producto",
                        "venta",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("precio", models.FloatField()),
                ("cantidad", models.FloatField()),
                (
                    "venta",
                    models.ForeignKey(
                        db_column="idventa",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ventasApp.cabeceraventa",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        db_column="idproducto",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ventasApp.producto",
                    ),
                ),
            ],
            options={
                "db_table": "detalleventas",
            },
        ),
    ]
