# Generated by Django 5.2.2 on 2025-06-27 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventasApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                ("idcategoria", models.AutoField(primary_key=True, serialize=False)),
                ("descripcion", models.CharField(max_length=30, unique=True)),
                ("estado", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
                "ordering": ["descripcion"],
            },
        ),
        migrations.CreateModel(
            name="Unidad",
            fields=[
                ("idunidad", models.AutoField(primary_key=True, serialize=False)),
                ("descripcion", models.CharField(max_length=30, unique=True)),
                ("estado", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                ("idproducto", models.AutoField(primary_key=True, serialize=False)),
                ("descripcion", models.CharField(max_length=40, unique=True)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("cantidad", models.IntegerField()),
                ("estado", models.BooleanField(default=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ventasApp.categoria",
                    ),
                ),
                (
                    "unidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ventasApp.unidad",
                    ),
                ),
            ],
        ),
    ]
