# Generated by Django 5.2.2 on 2025-06-27 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventasApp", "0002_categoria_unidad_producto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="categoria",
            field=models.ForeignKey(
                db_column="idcategoria",
                on_delete=django.db.models.deletion.CASCADE,
                to="ventasApp.categoria",
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="unidad",
            field=models.ForeignKey(
                db_column="idunidad",
                on_delete=django.db.models.deletion.CASCADE,
                to="ventasApp.unidad",
            ),
        ),
    ]
